import React from 'react';
import { 
  LayoutGrid, 
  Plus, 
  Barcode, 
  Tag, 
  Trash2, 
  Wallet, 
  Receipt, 
  ShoppingCart, 
  PieChart as PieChartIcon, 
  Bell, 
  HandCoins, 
  Factory, 
  CheckCheck, 
  List, 
  Users, 
  FileText, 
  TrendingDown, 
  Percent, 
  CalendarX, 
  BadgeDollarSign, 
  TableProperties, 
  TrendingUp, 
  ClipboardCheck, 
  Database, 
  PackageOpen, 
  BookOpen, 
  Settings as SettingsIcon, 
  RotateCcw,
  Car,
  Briefcase,
  Megaphone,
  Ticket,
  Download
} from 'lucide-react';

export const MENU_CATEGORIES = [
  { id: 'sales', label: 'فرۆشتن و پارە' },
  { id: 'inventory', label: 'کۆگا و بەرهەم' },
  { id: 'hr', label: 'کارمەندان و شۆفێران' },
  { id: 'livestock', label: 'ئاژەڵان' },
  { id: 'reports', label: 'ڕاپۆرتەکان' },
  { id: 'system', label: 'گشتی و ڕێکخستن' },
];

export const MENU_ITEMS: { id: string; label: string; icon: React.ReactNode; category: string }[] = [
  { id: 'add-product', label: 'کاڵای نوێ', icon: <Plus className="text-blue-500" />, category: 'inventory' },
  { id: 'returns', label: 'گەڕاندنەوەی کاڵا', icon: <RotateCcw className="text-orange-500" />, category: 'sales' },
  { id: 'shift-mgmt', label: 'سندوق و شەفت', icon: <Wallet className="text-emerald-600" />, category: 'sales' },
  { id: 'purchase-orders', label: 'داواکاری کڕین (PO)', icon: <ShoppingCart className="text-indigo-500" />, category: 'inventory' },
  { id: 'waste-log', label: 'بەهەدەردراو', icon: <Trash2 className="text-red-500" />, category: 'inventory' },
  { id: 'spending', label: 'خەرجی', icon: <Wallet className="text-red-600" />, category: 'sales' },
  { id: 'debt-in', label: 'وەرگرتنی قەرز', icon: <HandCoins className="text-green-600" />, category: 'sales' },
  { id: 'factory-debt', label: 'قەرزی کارگە', icon: <Factory className="text-slate-600" />, category: 'sales' },
  { id: 'suppliers-mgmt', label: 'بەڕێوەبردنی دابینکەر', icon: <Users className="text-blue-500" />, category: 'system' },
  { id: 'hr-mgmt', label: 'کارمەندان و مووچە', icon: <Users className="text-teal-600" />, category: 'hr' },
  { id: 'supplies', label: 'پێداویستی', icon: <PackageOpen className="text-orange-400" />, category: 'inventory' },
  { id: 'jard', label: 'جەرد کردن', icon: <ClipboardCheck className="text-slate-700" />, category: 'inventory' },
  { id: 'tasks', label: 'ئەرکەکان', icon: <CheckCheck className="text-indigo-500" />, category: 'system' },
  { id: 'assets', label: 'سەرمایەکان', icon: <Database className="text-emerald-600" />, category: 'system' },
  { id: 'vehicles', label: 'ئۆتۆمبێلەکان', icon: <Car className="text-teal-500" />, category: 'hr' },
  { id: 'drivers', label: 'شۆفێرەکان', icon: <Users className="text-amber-600" />, category: 'hr' },
  { id: 'projects', label: 'پڕۆژەکان', icon: <Briefcase className="text-purple-600" />, category: 'system' },
  { id: 'campaigns', label: 'کەمپەینەکان', icon: <Megaphone className="text-pink-500" />, category: 'system' },
  { id: 'tickets', label: 'تیکێتەکان', icon: <Ticket className="text-sky-500" />, category: 'system' },
  { id: 'livestock-mgmt', label: 'بەڕێوەبردنی ئاژەڵان', icon: <Users className="text-amber-600" />, category: 'livestock' },
  { id: 'milking-log', label: 'تۆماری شیر', icon: <Database className="text-blue-500" />, category: 'livestock' },
  { id: 'health-log', label: 'تۆماری تەندروستی', icon: <ClipboardCheck className="text-red-500" />, category: 'livestock' },
  { id: 'recipes', label: 'ڕەچەتەکان', icon: <List className="text-orange-500" />, category: 'inventory' },
  { id: 'production', label: 'بەرهەمهێنان', icon: <Factory className="text-blue-600" />, category: 'inventory' },
  { id: 'product-list', label: 'لیستی کاڵا', icon: <List className="text-purple-500" />, category: 'inventory' },
  { id: 'cat-mgmt', label: 'بەڕێوەبردنی بەش', icon: <LayoutGrid className="text-pink-500" />, category: 'system' },
  { id: 'customer-mgmt', label: 'بەڕێوەبردنی کڕیار', icon: <Users className="text-blue-600" />, category: 'sales' },
  { id: 'customer-list', label: 'لیستی کڕیار', icon: <Users className="text-blue-500" />, category: 'sales' },
  { id: 'customer-loyalty', label: 'خاڵەکانی کڕیار', icon: <HandCoins className="text-yellow-500" />, category: 'sales' },
  { id: 'bulk-import', label: 'هاوردەکردن (Excel)', icon: <Download className="text-emerald-500" />, category: 'inventory' },
  { id: 'barcode-gen', label: 'بارکۆد', icon: <Barcode className="text-slate-700" />, category: 'inventory' },
  { id: 'shelf-label', label: 'لایبڵی ڕەفە', icon: <Tag className="text-orange-500" />, category: 'inventory' },
  { id: 'sales-history', label: 'وەسڵەکان', icon: <Receipt className="text-teal-600" />, category: 'sales' },
  { id: 'payments', label: 'وەسڵی کردراو', icon: <CheckCheck className="text-blue-400" />, category: 'sales' },
  { id: 'cust-statement', label: 'کەشفی حیساب', icon: <FileText className="text-slate-500" />, category: 'sales' },
  { id: 'advanced-dashboard', label: 'داشبۆردی پێشکەوتوو', icon: <PieChartIcon className="text-indigo-600" />, category: 'reports' },
  { id: 'reports-hub', label: 'هەموو ڕاپۆرتەکان', icon: <LayoutGrid className="text-indigo-600" />, category: 'reports' },
  { id: 'qist-dash', label: 'داشبۆردی قیست', icon: <PieChartIcon className="text-indigo-500" />, category: 'reports' },
  { id: 'category-report', label: 'ڕاپۆرتی جۆرەکان', icon: <TrendingUp className="text-teal-500" />, category: 'reports' },
  { id: 'expense-report', label: 'ڕاپۆرتی خەرجی', icon: <TrendingDown className="text-orange-500" />, category: 'reports' },
  { id: 'qist-alerts', label: 'ئاگاداری', icon: <Bell className="text-yellow-500" />, category: 'reports' },
  { id: 'low-stock', label: 'کەشفی کەمبوو', icon: <TrendingDown className="text-red-400" />, category: 'reports' },
  { id: 'discounts', label: 'داشکان', icon: <Percent className="text-rose-500" />, category: 'reports' },
  { id: 'expired', label: 'بەسەرچوو', icon: <CalendarX className="text-red-600" />, category: 'reports' },
  { id: 'profits-rep', label: 'قازانجەکان', icon: <BadgeDollarSign className="text-emerald-600" />, category: 'reports' },
  { id: 'qist-rep', label: 'ڕاپۆرتی قیست', icon: <TableProperties className="text-indigo-400" />, category: 'reports' },
  { id: 'cash-rep', label: 'ڕاپۆرتی پارە', icon: <TrendingUp className="text-teal-500" />, category: 'reports' },
  { id: 'manual', label: 'بەکارهێنان', icon: <BookOpen className="text-blue-400" />, category: 'system' },
  { id: 'user-mgmt', label: 'بەڕێوەبردنی بەکارهێنەران', icon: <Users className="text-indigo-500" />, category: 'system' },
  { id: 'shop-request', label: 'داواکاری دوکان', icon: <ShoppingCart className="text-emerald-500" />, category: 'sales' },
  { id: 'shop-request-mgmt', label: 'بەڕێوەبردنی داواکاری دوکان', icon: <ShoppingCart className="text-blue-500" />, category: 'sales' },
  { id: 'settings', label: 'ڕێکخستن', icon: <SettingsIcon className="text-slate-800" />, category: 'system' },
];
